Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Semester_Project.Models;
using Semester_Project.Models.Interfaces;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Semester_Project.Controllers
{
    public class StudentController : Controller
    {
        private readonly IQuestionRepository questionRepository;
        public StudentController()
        {
            questionRepository = new QuestionRepository();
        }
        public IActionResult HomeStudent()
        {
            if (HttpContext.Session.GetString("UserName") != null)
            {
                List<Question> questions = questionRepository.Select(HttpContext.Session.GetString("UserName"));
                if (questions == null)
                {
                    return View("No Record Found!");
                }
                else
                {
                    return View(questions);
                }
            }
            else
            {
                return RedirectToAction("login", "Users");
            }
        }
        public IActionResult Ask()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ask(Question q)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Message = " Your Question has been added!";
                questionRepository.Add(q);
                questionRepository.Save();
                return View();
            }
            return View();
        }
        public ViewResult Edit(int id)
        {
            Question q = questionRepository.FindQuestion(id);
            return View(q);
        }
        [HttpPost]
        public ViewResult Edit(Question q)
        {
            questionRepository.UpdateQuestion(q);
            return View();
        }
        public IActionResult Delete(int id)
        {
            string name = questionRepository.GetUser(id);
            questionRepository.RemoveQuestion(id);
            return RedirectToAction("HomeStudent");
        }
    }
}

Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Semester_Project.Models;
using Semester_Project.Models.Interfaces;

namespace Semester_Project.Controllers
{
    public class TeacherController : Controller
    {
        private readonly IQuestionRepository questionRepository;
        public TeacherController() {
             questionRepository = new QuestionRepository();

        }
        public IActionResult HomeTeacher()
        {
            if (HttpContext.Session.GetString("UserName") != null)
            {
                List<Question> questions = questionRepository.Reterive();
                if (questions == null)
                {
                    return View("No Record Found!");
                }
                else
                {
                    return View(questions);
                }
            }
            else
            {
                return RedirectToAction("login", "Users");
            }
        }
        public IActionResult ViewQuestions()
        {
            List<Question> questions = questionRepository.Reterive();
            if (questions == null)
            {
                return View("No Record Found!");
            }
            else
            {
                return View(questions);
            }
        }
        public ViewResult Answer(int id)
        {
            Question q = questionRepository.FindQuestion(id);
            return View(q);
        }
        [HttpPost]
        public ViewResult Answer(Question q)
        {
            questionRepository.AnswerQuestion(q);
            return View();
        }
        public IActionResult GetSearchingData(string SearchBy, string SearchValue)
        {
            ProjectContext context = new ProjectContext();
            List<Question> questions = questionRepository.Reterive();
            if (SearchBy == "Tag")
            {
                try
                {
                    questions = context.Questions.Where(x => x.Tag.Equals(SearchValue) || SearchValue == null).ToList();
                }
                catch (FormatException)
                {
                    Console.WriteLine("{0} Is Not A TAG ", SearchValue);
                }
                Console.WriteLine(SearchValue);
                return Json(questions);
            }
            else
            {
                questions = context.Questions.Where(x => x.User.StartsWith(SearchValue) || SearchValue == null).ToList();
                return Json(questions);

            }
        }
    }
}

Views/Shared/_Layout.cshtml
<html>
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.3/font/bootstrap-icons.min.css">
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">  
    <link rel="stylesheet" href="~/css/style.css">  
    <link href="~/boxicons/css/boxicons.css" rel="stylesheet" />
    <link href="~/boxicons/css/boxicons.min.css" rel="stylesheet" />
    <link href="~/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
    </head>
    <body>
        <div>
        @RenderBody()
        </div>
        <!-- footer -->
        <footer class="bg-dark">
    <div class="footer-top">
        <div class="container">
            <div class="row gy-5">
                <div class="col-lg-3 col-sm-6">
                    <h5 class="mb-0 text-white">ASK ME</h5>
                    <div class="line"></div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, hic!</p>
                    <div class="social-icons">
                        <a href="#"><i class="ri-twitter-fill"></i></a>
                        <a href="#"><i class="ri-instagram-fill"></i></a>
                        <a href="#"><i class="ri-github-fill"></i></a>
                        <a href="#"><i class="ri-dribbble-fill"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <h5 class="mb-0 text-white">SERVICES</h5>
                    <div class="line"></div>
                    <ul>
                        <li><a href="#">Algorithm</a></li>
                        <li><a href="#">DataBase</a></li>
                        <li><a href="#">Operating System</a></li>
                        <li><a href="#">Data Structures</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <h5 class="mb-0 text-white">ABOUT</h5>
                    <div class="line"></div>
                    <ul>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Reviews</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <h5 class="mb-0 text-white">CONTACT</h5>
                    <div class="line"></div>
                    <ul>
                        <li>London, NY 3300</li>
                        <li>(414) 555 - 7686</li>
                        <li>www.example.com</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row g-4 justify-content-between">
                <div class="col-auto">
                    <p class="mb-0">© Copyright ASKME. All Rights Reserved</p>
                </div>
                <div class="col-auto">
                    <p class="mb-0">Designed with KR></p>
                </div>
            </div>
        </div>
    </div>
</footer>
    <p>@RenderSection("name", false)<p>
    </body>
</html>

Views/Shared/_Layout1.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <nav class="navbar navbar-expand-lg bg-white sticky-top">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="~/images/AsK.png" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto"  style="margin-left:auto; margin-right:0;">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Student" asp-action="HomeStudent">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Student" asp-action="Ask">Ask new question</a>
                    </li>
                    <li class="nav-item">
                       <a class="nav-link" href="../Users/Profile">@RenderSection("name",false)</a>
                    </li>
                </ul>
                <a href="/Users/logout" class="btn btn-brand ms-lg-3">LogOut</a>
            </div>
        </div>
    </nav>
        <div>
        @RenderBody()
        </div>
</body>

Views/Shared/_Layout2.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <nav class="navbar navbar-expand-lg bg-white sticky-top">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="~/images/AsK.png" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto"  style="margin-left:auto; margin-right:0;">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Teacher" asp-action="HomeTeacher">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Teacher" asp-action="ViewQuestions">View all questions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="../Users/Profile">@RenderSection("username", required:false)</a>
                    </li>
                </ul>
                <a href="/Users/logout" class="btn btn-brand ms-lg-3">LogOut</a>
            </div>
        </div>
    </nav>
        <div>
        @RenderBody()
        </div>
</body>